"""Added login functionality

Revision ID: 967467c955b9
Revises: 4bc55edac271
Create Date: 2026-05-07 13:31:27.256510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967467c955b9'
down_revision = '4bc55edac271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('like_id', sa.Integer(), nullable=False),
    sa.Column('liker_id', sa.Integer(), nullable=False),
    sa.Column('liked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_match', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('like_id')
    )
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index('ix_unique_like_direction', ['liker_id', 'liked_id'], unique=True)

    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_match_user_pair', ['user1_id', 'user2_id'], unique=False)

    op.create_table('notifications',
    sa.Column('notif_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notif_id')
    )
    op.create_table('preferences',
    sa.Column('pref_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gender_pref', sa.String(length=50), nullable=True),
    sa.Column('education_pref', sa.String(length=100), nullable=True),
    sa.Column('religion_pref', sa.String(length=100), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pref_id')
    )
    op.create_table('profile',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('saved_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saver_id', sa.Integer(), nullable=False),
    sa.Column('saved_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['saved_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['saver_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('saver_id', 'saved_id', name='_saver_saved_uc')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_changed_dob', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.create_index('ix_user_username', ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')
        batch_op.drop_index('ix_user_email')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('has_changed_dob')

    op.drop_table('messages')
    op.drop_table('saved_profiles')
    op.drop_table('profile')
    op.drop_table('preferences')
    op.drop_table('notifications')
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_match_user_pair')

    op.drop_table('matches')
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_like_direction')

    op.drop_table('like')
    # ### end Alembic commands ###
